- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: flake8
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
    - id: remove-tabs
    - id: remove-crlf
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
    - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.3.0
  hooks:
    - id: blacken-docs
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
    - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
    - id: isort
      exclude: ^docs/conf\.py$
